name: Deploying latest

on:
    push:
        branches:
            - main

jobs:
    deploy:
        timeout-minutes: 3

        name: Deploy rewards API [sandbox]
        runs-on: ubuntu-latest

        steps:
            - name: Repository checkout
              uses: actions/checkout@v2

            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AWS_CEREBRO_DEV_HOST }}
                  username: ${{ secrets.AWS_CEREBRO_USER }}
                  key: ${{ secrets.AWS_CEREBRO_SANDBOX_KEY }}

                  script: |
                      cd ${{ secrets.CEREBRO_SANDBOX_PWD }}
                      bash deploy.sh dev
